config/routes.rb
Rails.application.routes.draw do
  resources :notes

  root 'notes#index'
  # This defines root page or landing page when you first arrive at website. 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @note = Note.all
    # This is storing all instances of class Note in varialbe @notes
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end
  
  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

private
def note_params
  params.require(:note).permit(:title, :note)
  
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Notes', notes_path %>
<%= link_to 'Back', notes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<body>
  <hr>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <hr>
</body>

<h1>EDIT NOTE</h1>

<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :note %>
  <%= f.text_area :note %>

  <%= f.submit %>
<% end %>

app/views/notes/index.html.erb
<body>
  <hr>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <hr>
</body>
<h1>NOTES</h1>
<%= link_to "New Note", new_note_path%>
<% @note.each do |note| %>
  <h2><%= note.title %></h2>
  <%= link_to 'Show Note', note_path(note) %>
  <%= link_to 'Delete Note', note, method: :delete %>
  <%= link_to 'Edit Note', edit_note_path(note) %>
<% end %>

app/views/notes/new.html.erb
<body>
  <hr>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <hr>
</body>

<h1>NEW NOTE</h1>

<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :note %>
  <%= f.text_area :note %>

  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<body>
  <hr>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <hr>
</body>

<h1>Read Note</h1>
<%= @note.title %>
<%= @note.note%>